### ISSUE TITLE
SetPowerURL does not work if character % is part of the web link (e.g. Tasmota command for relays)

### ISSUE THREAD

**Issue by yokokito** [dbochicchio/vera-VirtualDevices#1]
Hi Daniele,
I´m using your fantastic plugin (thanks !) and I realise of a problem when commanding Tasmota devices.
The web command for this kind of devices is http://<ip>/cm?cmnd=Power%20TOGGLE
In my specific case http://192.168.0.118/cm?cmnd=Power1%20off
The plugin (created deviced) does not work properly with this link.
Changing the "SetPowerURL" to other link's device that i have (e.g. Shellly), the link works (it does not contain %)
Trying the http://192.168.0.118/cm?cmnd=Power1%20off directly in Chrome, it works.
So, it seems it is a problem with the plugin implementation.

Just for your consideration.
Kind regards
César

**Comment by dbochicchio** [comment]
Hi César, thanks for your kind words!
Yes, since it's using LUA replace, % will break it. I'll remove it next version (it was used when only one command was presente for both on and off), but in the meantime, you could just use _+_ instread of _%20_.

This will work: http://192.168.0.118/cm?cmnd=Power1+off and it's perfectly fine as an encoded URL.
